import React from 'react';
import { Link } from 'react-router-dom';
import {delay, motion} from "framer-motion"


const Queries = () => {
  return (
    <motion.div className="flex flex-col items-center my-20 px-4"
        initial = {{opacity:0.2, y:100}} 
        transition={{duration:1}}
        whileInView={{opacity:1, y:0}}
        viewport={{once:true}}
        >
      <h2 className="text-3xl sm:text-4xl font-semibold mb-12 text-center border-b-4 border-indigo-500 pb-2">
        Frequently Asked Questions
      </h2>
      <div className="w-full max-w-3xl space-y-12 mr-40 ">
        <div>
        <hr className="border-gray-200 my-6" />
          <p className="text-2xl font-medium text-gray-800 mb-2">Is commercial use allowed?</p>
          <p className="text-xl text-gray-700">
            Yes, commercial use is permitted for the generated images. You may utilize these images for any legal purposes.
            For full details, please refer to our
            <span className="text-blue-500 cursor-pointer"> <Link to="/terms-of-service">Terms of Service</Link></span>.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>

        <div>
        <hr className="border-gray-200 my-6" />
          <p className="text-2xl font-medium text-gray-800 mb-1.5">Who owns the output?</p>
          <p className="text-xl text-gray-700">
            The generated images are considered public domain and hence, they have no owner.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>

        <div>
        <hr className="border-gray-200 my-6" />
          <p className="text-2xl font-medium text-gray-800 mb-1.5">Is there a copyright on the output?</p>
          <p className="text-xl text-gray-700">
            The images generated by the AI are not subject to copyright.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>

        <div>
        <hr className="border-gray-200 my-6" />
          <p className="text-2xl font-medium text-gray-800 mb-1.5">Can I get higher resolution or higher quality images?</p>
          <p className="text-xl text-gray-700">
            Currently, we do not offer images in higher resolutions or qualities. The available quality will improve over time.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>

        <div>
        <hr className="border-gray-200 my-6" />
          <p className="text-2xl font-medium text-gray-800 mb-1.5">Is the quality of the images suitable for printing?</p>
          <p className="text-xl text-gray-700">
            The quality is generally sufficient for printing smaller images. However, larger prints might appear blurry.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>
      </div>
    </motion.div>
  );
};

export default Queries;