import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import {delay, motion} from "framer-motion"



const Queries = () => {
  
  const navigate = useNavigate();

  return (
    <motion.div className="flex flex-col items-center my-20 px-4"
        initial = {{opacity:0.2, y:100}} 
        transition={{duration:1}}
        whileInView={{opacity:1, y:0}}
        viewport={{once:true}}
        >
      <h2 className={`text-3xl sm:text-4xl font-semibold mb-12 text-center border-b-4 text-white border-indigo-500 pb-2 dark:text-black`}>
        Frequently Asked Questions
      </h2>
      <div className="w-full max-w-3xl space-y-12 mr-40 ">
        <div>
        <hr className="border-gray-200 my-6" />
          <p className={`text-2xl font-medium mb-2 text-white dark:text-gray-800`}>Is commercial use allowed?</p>
          <p className={`text-xl text-white/70 dark:text-black`}>
            Yes, commercial use is permitted for the generated images. You may utilize these images for any legal purposes.
            For full details, please refer to our
            <span className="text-blue-500 cursor-pointer"> <button onClick={()=>{navigate('/terms-of-service'); scrollTo(0,0)}}>Terms of Service</button></span>.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>

        <div>
        <hr className="border-gray-200 my-6" />
          <p className={`text-2xl font-medium  mb-1.5 text-white dark:text-gray-800`}>Who owns the output?</p>
          <p className="text-xl text-white/70 dark:text-gray-700">
            The generated images are considered public domain and hence, they have no owner.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>

        <div>
        <hr className="border-gray-200 my-6" />
          <p className="text-2xl font-medium text-white dark:text-gray-800 mb-1.5">Is there a copyright on the output?</p>
          <p className="text-xl text-white/70 dark:text-gray-700">
            The images generated by the AI are not subject to copyright.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>

        <div>
        <hr className="border-gray-200 my-6" />
          <p className="text-2xl font-medium text-white dark:text-gray-800 mb-1.5">Can I get higher resolution or higher quality images?</p>
          <p className="text-xl text-white/70 dark:text-gray-700">
            Currently, we do not offer images in higher resolutions or qualities. The available quality will improve over time.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>

        <div>
        <hr className="border-gray-200 my-6" />
          <p className="text-2xl font-medium text-white dark:text-gray-800 mb-1.5">Is the quality of the images suitable for printing?</p>
          <p className="text-xl text-white/70  dark:text-gray-700">
            The quality is generally sufficient for printing smaller images. However, larger prints might appear blurry.
          </p>
          <hr className="border-gray-200 my-6" />
        </div>
      </div>
    </motion.div>
  );
};

export default Queries;