import userModel from "../models/userModel.js";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";
import razorpay from "razorpay";
import transactionModels from "../models/transactionModels.js";
import transporter from "../config/nodemailer.js";

// register
export const register = async (req, res) => {
    try {
        const { name, email, password } = req.body

        if (!name || !email || !password) {
            return res.json({ success: false, message: "Missing Details!" })
        }
        // salt is for password security and salt is generated by random alg and it generates diff hash eventhough the pwd is same
        //Default salt value is 10. The more the number the more secure the pwd, but slower the hashing
        const salt = await bcrypt.genSalt(10)
        // password + salt = hashedPassword
        const hashedPassword = await bcrypt.hash(password, salt)

        // storing user details in userData and we have created userData from the user response
        const userData = {
            name,
            email,
            password: hashedPassword
        }
        // Storing the userData in mongoDb
        const newUser = new userModel(userData);
        const user = await newUser.save()

        // whenever user is created in the db it automatically creates id using user_id and with this unique id will generate token
        const token = jwt.sign({ id: user._id }, process.env.SECRET_KEY, { expiresIn: '8h' })

        //Sending Welcome email
        const mailOptions = {
            from: process.env.SMTP_SENDER_EMAIL,
            to: email,
            subject: "🎉 Welcome to True SevAI!",
            text: `Hi ${name}!,
        
        Welcome to True SevAI! We're excited to have you on board.
        
        Your account has been successfully created with the email address: ${email}
        
        Explore our platform and let us know if you need any help getting started.
        
        Best regards,  
        The True SevAI Team`
        };

        await transporter.sendMail(mailOptions);

        res.json({ success: true, token, user: { name: user.name } })

    } catch (error) {
        console.log(error)
        res.json({ success: false, message: error.message })
    }
}

// login
export const login = async (req, res) => {
    try {
        // retriving email and pwd from body
        const { email, password } = req.body;
        const user = await userModel.findOne({ email });

        if (!user) {
            return res.json({ success: false, message: "User does not exist!" })
        }

        // if user is exist will check the password using compare method
        const isMatch = await bcrypt.compare(password, user.password)

        if (isMatch) {
            const token = jwt.sign({ id: user._id }, process.env.SECRET_KEY, { expiresIn: '8h' })

            res.json({ success: true, token, user: { name: user.name } })

        } else {
            return res.json({ success: false, message: "Invalid credentials" })
        }

    } catch (error) {
        console.log(error)
        res.json({ success: false, message: error.message })
    }
}
// userCredits
export const usesrCredits = async (req, res) => {
    try {
        const { userId } = req.body

        const user = await userModel.findById(userId)
        res.json({ success: true, credits: user.creditBalance, user: { name: user.name } })
    } catch (error) {
        console.log(error)
        res.json({ success: false, message: error.message })
    }
}

// payment gateway
const razorpayInstance = new razorpay({
    key_id: process.env.RAZORPAY_KEY_ID,
    key_secret: process.env.RAZORPAY_KEY_SECRET
});

export const razorpayGateway = async (req, res) => {
    try {
        const { userId, planId } = req.body

        const user = await userModel.findById(userId)

        if (!userId || !planId) {
            return res.json({ success: false, message: "Missing Details" })
        }
        let credits, plan, amount, date

        // based on planId we create credits, amount
        switch (planId) {
            case "Basic":
                plan = "Basic",
                    credits = 100,
                    amount = 10
                break;

            case "Advanced":
                plan = "Advanced",
                    credits = 500,
                    amount = 50
                break;

            case "Business":
                plan = "Business",
                    credits = 5000,
                    amount = 250
                break;

            default:
                return res.json({ success: false, message: "Plan not found" });
        }
        // for storing the current date
        date = Date.now();

        // store plan, credits, amount, date 
        const transactionData = {
            userId, plan, credits, amount, date
        }
        // It will store the transac data in mongodb
        const newTransaction = await transactionModels.create(transactionData);

        // creating options in order to create orders
        // calculating amount with 100. Coz razorpay consider amount decimals for eg. $155 will be 1.55 so multiple with 100
        // receipt in order to verify the razorpay payment for that we have to generate unique ._id
        const options = {
            amount: amount * 100,
            currency: process.env.CURRENCY,
            receipt: newTransaction._id
        }
        // Creating order
        await razorpayInstance.orders.create(options, (error, order) => {
            if (error) {
                console.log(error)
                return res.json({ success: false, message: error })
            }
            res.json({ success: true, order })   
        })

    } catch (error) {
        console.log(error)
        res.json({ success: false, message: error.message })
    }
}

export const verifyRazorpay = async (req, res) => {
    try {

        const { razorpay_order_id } = req.body;

        const orderInfo = await razorpayInstance.orders.fetch(razorpay_order_id);

        if (orderInfo.status === "paid") {
            const transactionData = await transactionModels.findById(orderInfo.receipt)

            if (transactionData.payment) {
                return res.json({ success: false, message: "Payment Failed!" })
            }
            const userData = await userModel.findById(transactionData.userId)

            const creditBalance = userData.creditBalance + transactionData.credits

            await userModel.findByIdAndUpdate(userData._id, { creditBalance })

            await transactionModels.findByIdAndUpdate(transactionData._id, { payment: true })

            res.json({ success: true, message: "Credits Added" })
        } else {
            res.json({ success: false, message: "Payment Failed" })
        }

    } catch (error) {
        console.log(error)
        res.json({ success: false, message: error.message });
    }
}


// Send password and Reset Otp
export const sendResetOtp = async(req, res) =>{
    const {email} = req.body;

    if (!email){
        return res.json({success: false, message: 'Email is required'})
    }

    try {

        const user = await userModel.findOne({email});
        if (!user){
            return res.json({success: false, message: 'User not found'});
        }

        const otp = String(Math.floor(100000 + Math.random() * 900000));

        user.resetOtp = otp;
        user.resetOtpExpiresAt = Date.now() + 15 * 60 * 1000;

        // using this user.save() user's otp and otp expire time saves in db
        await user.save();

        const mailOptions = {
            from: process.env.SMTP_SENDER_EMAIL,
            to: user.email,
            subject: "🔐 Password Reset OTP",
            text: `Hi ${user.name || "there"},\n\nYou requested to reset your password.
            \n\nYour One-Time Password (OTP) is: ${otp}\n\nPlease enter this OTP to proceed with resetting your password. 
            The OTP is valid for the next 10 minutes.\n\nIf you did not request this, please ignore this email.
            \n\nBest regards,\nThe True SevAI Team`
        };
        

        await transporter.sendMail(mailOptions)

        return res.json({success: true, message: 'OTP sent your registered email address.'})

    } catch (error) {
        return res.json({success: false, message: error.message})
    }
}

// Reset User Password
export const resetPassword = async(req, res) =>{
    const {email, otp, newPassword} = req.body;

    if (!email || !otp || !newPassword) {
        return res.json({success: false, message: 'Email, otp and new password is required to reset the password.'})
    }
    try {

        const user = await userModel.findOne({email});

        if (!user){
            return res.json({success: false, message: 'User not found'})
        }

        if(user.resetOtp === "" || user.resetOtp !== otp){
            return res.json({success: false, message: 'Invalid OTP'})
        }

        if (user.resetOtpExpiresAt < Date.now()){
            return res.json({success: false, message: "OTP Expired"})
        }

        const hashedPassword = await bcrypt.hash(newPassword, 10);
        user.password = hashedPassword;
        user.resetOtp = '';
        user.resetOtpExpiresAt = 0;

        await user.save();

        return res.json({success: true, message: "Password has been reset successfully"})
        
    } catch (error) {
        return res.json({success: false, message: error.message})
    }
}

// Verify OTP
export const verifyResetOtp = async (req, res) => {
    const { email, otp } = req.body;

    if (!email || !otp) {
        return res.json({ success: false, message: "Email and OTP are required" });
    }

    try {
        const user = await userModel.findOne({ email });

        if (!user) {
            return res.json({ success: false, message: "User not found" });
        }

        if (user.resetOtp !== otp) {
            return res.json({ success: false, message: "Invalid OTP" });
        }

        if (user.resetOtpExpiresAt < Date.now()) {
            return res.json({ success: false, message: "OTP expired" });
        }

        return res.json({ success: true, message: "OTP verified successfully" });

    } catch (error) {
        return res.json({ success: false, message: error.message });
    }
};